from __future__ import annotations

import collections.abc
import datetime
import os
import typing

import numpy
import numpy.typing

import spark_dsg

__all__: list[str] = [
    "AgentNodeAttributes",
    "BoundaryInfo",
    "BoundingBox",
    "BoundingBoxType",
    "BoxResult2D",
    "Color",
    "DsgLayers",
    "EdgeAttributes",
    "KhronosObjectAttributes",
    "Labelspace",
    "LayerKey",
    "LayerView",
    "Mesh",
    "NearestVertexInfo",
    "NodeAttributes",
    "NodeSymbol",
    "ObjectNodeAttributes",
    "PartitionId",
    "Place2dNodeAttributes",
    "PlaceNodeAttributes",
    "Quaternion",
    "RoomNodeAttributes",
    "SceneGraph",
    "SceneGraphEdge",
    "SceneGraphLayer",
    "SceneGraphNode",
    "SemanticNodeAttributes",
    "TravNodeAttributes",
    "TraversabilityNodeAttributes",
    "TraversabilityState",
    "colorbrewer_color",
    "compute_ancestor_bounding_box",
    "distinct_150_color",
    "enable_short_serialization_message",
    "get_2d_convex_hull",
    "get_min_2d_box",
    "rainbow_color",
    "version",
]

class AgentNodeAttributes(NodeAttributes):
    timestamp: datetime.timedelta
    world_R_body: Quaternion
    def __init__(self) -> None: ...
    @property
    def dbow_ids(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.uint32], "[m, 1]"]: ...
    @dbow_ids.setter
    def dbow_ids(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32, "[m, 1]"]
    ) -> None: ...
    @property
    def dbow_values(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]: ...
    @dbow_values.setter
    def dbow_values(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, 1]"]
    ) -> None: ...
    @property
    def external_key(self) -> int: ...
    @external_key.setter
    def external_key(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def observed_semantic_labels(self) -> list[int]: ...
    @observed_semantic_labels.setter
    def observed_semantic_labels(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...

class BoundaryInfo:
    def __init__(self) -> None: ...
    @property
    def max(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]: ...
    @max.setter
    def max(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]
    ) -> None: ...
    @property
    def min(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]: ...
    @min.setter
    def min(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]
    ) -> None: ...
    @property
    def states(
        self,
    ) -> typing.Annotated[list[list[TraversabilityState]], "FixedSize(4)"]: ...
    @states.setter
    def states(
        self,
        arg0: typing.Annotated[
            collections.abc.Sequence[collections.abc.Sequence[TraversabilityState]],
            "FixedSize(4)",
        ],
    ) -> None: ...

class BoundingBox:
    type: BoundingBoxType
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"],
        arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"],
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"],
        arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"],
        arg2: typing.SupportsFloat | typing.SupportsIndex,
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        arg0: BoundingBoxType,
        arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"],
        arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"],
        arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 3]"],
    ) -> None: ...
    def __repr__(self) -> str: ...
    def approx_iou(
        self,
        other: BoundingBox,
        samples: typing.SupportsInt | typing.SupportsIndex = 1000,
    ) -> float: ...
    def compute_iou(
        self,
        other: BoundingBox,
        samples: typing.SupportsInt | typing.SupportsIndex = 1000,
    ) -> float: ...
    def contains(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]
    ) -> bool: ...
    def corners(
        self,
    ) -> typing.Annotated[
        list[typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]],
        "FixedSize(8)",
    ]: ...
    def has_rotation(self) -> bool: ...
    def intersects(self, arg0: BoundingBox) -> bool: ...
    def is_valid(self) -> bool: ...
    def volume(self) -> float: ...
    @property
    def dimensions(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]: ...
    @dimensions.setter
    def dimensions(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]
    ) -> None: ...
    @property
    def max(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]: ...
    @property
    def min(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]: ...
    @property
    def world_P_center(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]: ...
    @world_P_center.setter
    def world_P_center(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]
    ) -> None: ...
    @property
    def world_R_center(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 3]"]: ...
    @world_R_center.setter
    def world_R_center(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 3]"]
    ) -> None: ...

class BoundingBoxType:
    """
    Members:

      INVALID

      AABB

      OBB

      RAABB
    """

    AABB: typing.ClassVar[BoundingBoxType]  # value = <BoundingBoxType.AABB: 1>
    INVALID: typing.ClassVar[BoundingBoxType]  # value = <BoundingBoxType.INVALID: 0>
    OBB: typing.ClassVar[BoundingBoxType]  # value = <BoundingBoxType.OBB: 2>
    RAABB: typing.ClassVar[BoundingBoxType]  # value = <BoundingBoxType.RAABB: 3>
    __members__: typing.ClassVar[
        dict[str, BoundingBoxType]
    ]  # value = {'INVALID': <BoundingBoxType.INVALID: 0>, 'AABB': <BoundingBoxType.AABB: 1>, 'OBB': <BoundingBoxType.OBB: 2>, 'RAABB': <BoundingBoxType.RAABB: 3>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(
        self, state: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class BoxResult2D:
    def __repr__(self) -> str: ...
    @property
    def center(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, 1]"]: ...
    @center.setter
    def center(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"]
    ) -> None: ...
    @property
    def dims(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, 1]"]: ...
    @dims.setter
    def dims(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"]
    ) -> None: ...
    @property
    def yaw(self) -> float: ...
    @yaw.setter
    def yaw(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class Color:
    def __init__(self) -> None: ...
    def to_float_array(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def g(self) -> int: ...
    @g.setter
    def g(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def r(self) -> int: ...
    @r.setter
    def r(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...

class DsgLayers:
    AGENTS: typing.ClassVar[str] = "AGENTS"
    BUILDINGS: typing.ClassVar[str] = "BUILDINGS"
    MESH_PLACES: typing.ClassVar[str] = "MESH_PLACES"
    OBJECTS: typing.ClassVar[str] = "OBJECTS"
    PLACES: typing.ClassVar[str] = "PLACES"
    ROOMS: typing.ClassVar[str] = "ROOMS"
    SEGMENTS: typing.ClassVar[str] = "SEGMENTS"
    TRAVERSABILITY: typing.ClassVar[str] = "TRAVERSABILITY"
    @staticmethod
    def name_to_layer_id(name: str) -> LayerKey | None: ...

class EdgeAttributes:
    _metadata: _Metadata
    weighted: bool
    def __copy__(self) -> EdgeAttributes: ...
    def __deepcopy__(self, memo: dict) -> EdgeAttributes: ...
    def __init__(self) -> None: ...
    @property
    def metadata(self) -> spark_dsg.Metadata: ...
    @property
    def weight(self) -> float: ...
    @weight.setter
    def weight(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class KhronosObjectAttributes(ObjectNodeAttributes):
    def __init__(self) -> None: ...
    def mesh(self) -> Mesh: ...
    @property
    def details(self) -> dict[str, list[int]]: ...
    @property
    def dynamic_object_points(
        self,
    ) -> list[
        list[typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]]
    ]: ...
    @property
    def first_observed_ns(self) -> list[int]: ...
    @property
    def last_observed_ns(self) -> list[int]: ...
    @property
    def trajectory_positions(
        self,
    ) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]]: ...
    @property
    def trajectory_timestamps(self) -> list[int]: ...

class Labelspace:
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(
        self,
        arg0: collections.abc.Mapping[typing.SupportsInt | typing.SupportsIndex, str],
    ) -> None: ...
    def get_category(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> str | None: ...
    def get_label(self, arg0: str) -> int | None: ...
    def get_node_category(
        self, node: SceneGraphNode, unknown_name: str = "UNKNOWN"
    ) -> str: ...
    @property
    def labels_to_names(self) -> dict[int, str]: ...
    @property
    def names_to_labels(self) -> dict[str, int]: ...

class LayerKey:
    @staticmethod
    def __hash__(key): ...
    def __eq__(self, arg0: typing.Any) -> bool: ...
    def __gt__(self, arg0: LayerKey) -> bool: ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @typing.overload
    def __init__(
        self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: PartitionId | int
    ) -> None: ...
    def __lt__(self, arg0: LayerKey) -> bool: ...
    def __ne__(self, arg0: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    @property
    def layer(self) -> int: ...
    @layer.setter
    def layer(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def partition(self) -> int: ...
    @partition.setter
    def partition(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...

class LayerView:
    @staticmethod
    def to_torch(
        G: SceneGraphLayer | LayerView,
        node_converter: typing.Callable[
            [SceneGraph | SceneGraphLayer | LayerView, SceneGraphNode], numpy.ndarray
        ],
        edge_converter: typing.Callable[
            [SceneGraph | SceneGraphLayer | LayerView, SceneGraphEdge], numpy.ndarray
        ]
        | None = None,
        double_precision: bool = False,
    ):
        """

        Convert a scene graph layer to a homogeneous pytorch geometric data structure.

        Args:
            G: scene graph layer to convert
            node_converter: function to generate input node features
            edge_converter: optional function to generate input edge features
            double_precision: whether or not output data attributes have double precision.

        Raises:
            ValueError: If pytorch geometric can't be found for the conversion

        Returns:
            pytorch_geometric.Data: homogeneous pytorch_geometric graph representing the
                scene graph layer.
        """
    def connected_components(self) -> list[list[int]]: ...
    def find_edge(
        self, arg0: NodeSymbol | int, arg1: NodeSymbol | int
    ) -> SceneGraphEdge | None: ...
    def find_node(self, arg0: NodeSymbol | int) -> SceneGraphNode | None: ...
    def get_edge(
        self, arg0: NodeSymbol | int, arg1: NodeSymbol | int
    ) -> SceneGraphEdge: ...
    def get_node(self, arg0: NodeSymbol | int) -> SceneGraphNode: ...
    def get_position(
        self, arg0: NodeSymbol | int
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    def has_edge(self, arg0: NodeSymbol | int, arg1: NodeSymbol | int) -> bool: ...
    def has_node(self, arg0: NodeSymbol | int) -> bool: ...
    def num_edges(self) -> int: ...
    def num_nodes(self) -> int: ...
    def shortest_path(
        self, arg0: NodeSymbol | int, arg1: NodeSymbol | int
    ) -> list[int]: ...
    @property
    def edges(self) -> collections.abc.Iterator[SceneGraphEdge]: ...
    @property
    def id(self) -> int: ...
    @property
    def key(self) -> LayerKey: ...
    @property
    def nodes(self) -> collections.abc.Iterator[SceneGraphNode]: ...
    @property
    def partition(self) -> int: ...

class Mesh:
    @staticmethod
    def from_binary(arg0: bytes) -> Mesh: ...
    @staticmethod
    def from_json(arg0: str) -> Mesh: ...
    @staticmethod
    def load(arg0: os.PathLike | str | bytes) -> Mesh: ...
    def __iadd__(self, arg0: Mesh) -> Mesh: ...
    def __init__(
        self,
        has_colors: bool = True,
        has_timestamps: bool = True,
        has_labels: bool = True,
        has_first_seen_stamps: bool = True,
    ) -> None: ...
    def append(self, arg0: Mesh) -> bool: ...
    def clear(self) -> None: ...
    def clone(self) -> Mesh: ...
    def color(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> Color: ...
    def empty(self) -> bool: ...
    def erase_faces(
        self,
        indices: collections.abc.Set[typing.SupportsInt | typing.SupportsIndex],
        update_vertices: bool = True,
    ) -> None: ...
    def erase_vertices(
        self, indices: collections.abc.Set[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    def face(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> typing.Annotated[list[int], "FixedSize(3)"]: ...
    def first_seen_timestamp(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> int: ...
    def get_faces(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"]: ...
    def get_labels(self) -> list[int]: ...
    def get_vertices(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]: ...
    def label(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int: ...
    def memory_usage(self) -> int: ...
    def num_faces(self) -> int: ...
    def num_vertices(self) -> int: ...
    def pos(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]: ...
    def reserve_vertices(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    def resize_faces(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def resize_vertices(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    def save(self, arg0: os.PathLike | str | bytes) -> None: ...
    def set_color(
        self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: Color
    ) -> None: ...
    def set_face(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.Annotated[
            collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex],
            "FixedSize(3)",
        ],
    ) -> None: ...
    def set_faces(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[m, n]"]
    ) -> None: ...
    def set_first_seen_timestamp(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.SupportsInt | typing.SupportsIndex,
    ) -> None: ...
    def set_label(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.SupportsInt | typing.SupportsIndex,
    ) -> None: ...
    def set_pos(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"],
    ) -> None: ...
    def set_timestamp(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.SupportsInt | typing.SupportsIndex,
    ) -> None: ...
    def set_vertices(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]
    ) -> None: ...
    def timestamp(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int: ...
    def to_binary(self) -> bytes: ...
    def to_json(self) -> str: ...
    def transform(
        self,
        rotation: typing.Annotated[
            numpy.typing.ArrayLike, numpy.float64, "[3, 3]"
        ] = ...,
        translation: typing.Annotated[
            numpy.typing.ArrayLike, numpy.float64, "[3, 1]"
        ] = ...,
    ) -> None: ...

class NearestVertexInfo:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def block(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[3, 1]"]: ...
    @block.setter
    def block(
        self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[3, 1]"]
    ) -> None: ...
    @property
    def label(self) -> int | None: ...
    @label.setter
    def label(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None: ...
    @property
    def vertex(self) -> int: ...
    @vertex.setter
    def vertex(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def voxel_pos(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    @voxel_pos.setter
    def voxel_pos(
        self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]
    ) -> None: ...

class NodeAttributes:
    _metadata: _Metadata
    is_active: bool
    is_predicted: bool
    def __copy__(self) -> NodeAttributes: ...
    def __deepcopy__(self, memo: dict) -> NodeAttributes: ...
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def transform(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]
    ) -> NodeAttributes: ...
    @property
    def last_update_time_ns(self) -> int: ...
    @last_update_time_ns.setter
    def last_update_time_ns(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def metadata(self) -> spark_dsg.Metadata: ...
    @property
    def position(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    @position.setter
    def position(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]
    ) -> None: ...

class NodeSymbol:
    def __eq__(self, arg0: typing.Any) -> bool: ...
    def __hash__(self) -> int: ...
    @typing.overload
    def __init__(
        self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __ne__(self, arg0: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def category_id(self) -> int: ...
    @property
    def value(self) -> int: ...
    def str(self, literal: bool = True) -> str: ...

class ObjectNodeAttributes(SemanticNodeAttributes):
    registered: bool
    world_R_object: Quaternion
    def __init__(self) -> None: ...
    @property
    def mesh_connections(self) -> list[int]: ...
    @mesh_connections.setter
    def mesh_connections(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...

class PartitionId:
    @typing.overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @typing.overload
    def __init__(self, arg0: str) -> None: ...

class Place2dNodeAttributes(SemanticNodeAttributes):
    has_active_mesh_indices: bool
    need_finish_merge: bool
    def __init__(self) -> None: ...
    @property
    def boundary(
        self,
    ) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]]: ...
    @boundary.setter
    def boundary(
        self,
        arg0: collections.abc.Sequence[
            typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]
        ],
    ) -> None: ...
    @property
    def boundary_connections(self) -> list[int]: ...
    @boundary_connections.setter
    def boundary_connections(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def ellipse_centroid(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    @ellipse_centroid.setter
    def ellipse_centroid(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]
    ) -> None: ...
    @property
    def ellipse_matrix_compress(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]: ...
    @ellipse_matrix_compress.setter
    def ellipse_matrix_compress(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 2]"]
    ) -> None: ...
    @property
    def ellipse_matrix_expand(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]: ...
    @ellipse_matrix_expand.setter
    def ellipse_matrix_expand(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 2]"]
    ) -> None: ...
    @property
    def max_mesh_index(self) -> int: ...
    @max_mesh_index.setter
    def max_mesh_index(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def mesh_connections(self) -> list[int]: ...
    @mesh_connections.setter
    def mesh_connections(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def min_mesh_index(self) -> int: ...
    @min_mesh_index.setter
    def min_mesh_index(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...

class PlaceNodeAttributes(SemanticNodeAttributes):
    active_frontier: bool
    anti_frontier: bool
    need_cleanup: bool
    orientation: Quaternion
    real_place: bool
    def __init__(self) -> None: ...
    @property
    def deformation_connections(self) -> list[int]: ...
    @deformation_connections.setter
    def deformation_connections(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def distance(self) -> float: ...
    @distance.setter
    def distance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def frontier_scale(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    @frontier_scale.setter
    def frontier_scale(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]
    ) -> None: ...
    @property
    def mesh_vertex_labels(self) -> list[int]: ...
    @mesh_vertex_labels.setter
    def mesh_vertex_labels(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def num_basis_points(self) -> int: ...
    @num_basis_points.setter
    def num_basis_points(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def num_frontier_voxels(self) -> int: ...
    @num_frontier_voxels.setter
    def num_frontier_voxels(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def pcl_mesh_connections(self) -> list[int]: ...
    @pcl_mesh_connections.setter
    def pcl_mesh_connections(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def voxblox_mesh_connections(self) -> list[NearestVertexInfo]: ...
    @voxblox_mesh_connections.setter
    def voxblox_mesh_connections(
        self, arg0: collections.abc.Sequence[NearestVertexInfo]
    ) -> None: ...

class Quaternion:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(
        self,
        arg0: typing.SupportsFloat | typing.SupportsIndex,
        arg1: typing.SupportsFloat | typing.SupportsIndex,
        arg2: typing.SupportsFloat | typing.SupportsIndex,
        arg3: typing.SupportsFloat | typing.SupportsIndex,
    ) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def w(self) -> float: ...
    @w.setter
    def w(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class RoomNodeAttributes(SemanticNodeAttributes):
    def __init__(self) -> None: ...
    @property
    def semantic_class_probabilities(self) -> dict[str, float]: ...
    @semantic_class_probabilities.setter
    def semantic_class_probabilities(
        self,
        arg0: collections.abc.Mapping[str, typing.SupportsFloat | typing.SupportsIndex],
    ) -> None: ...

class SceneGraph:
    _metadata: _Metadata
    mesh: Mesh
    @staticmethod
    def from_binary(arg0: bytes) -> SceneGraph: ...
    @staticmethod
    def get_layer_id(graph, name): ...
    @staticmethod
    def load(arg0: os.PathLike | str | bytes) -> SceneGraph: ...
    @staticmethod
    def to_torch(G: SceneGraph, *args, use_heterogeneous: bool = True, **kwargs):
        """

        Convert a scene graph to a pytorch geometric graph.

        Args:
            G: scene graph to convert
            *args: All positional arguments for scene_graph_to_torch_homogeneous or
                   scene_graph_to_torch_heterogeneous
            use_heterogeneous: Whether or not to use a heterogeneous pytorch geometric graph
                structure
            **kwargs: All arguments for scene_graph_to_torch_homogeneous or
                      scene_graph_to_torch_heterogeneous

        Raises:
            ValueError: If pytorch geometric can't be found for the conversion

        Returns:
            Union[pytorch_geometric.HeteroData, pytorch_geometric.Data]: pytorch geometric
                data representing the scene graph depending on use_heterogeneous.
        """
    def __deepcopy__(self, arg0: typing.Any) -> SceneGraph: ...
    @typing.overload
    def __init__(self, empty: bool = False) -> None: ...
    @typing.overload
    def __init__(
        self,
        layer_keys: collections.abc.Sequence[LayerKey],
        layer_names: collections.abc.Mapping[str, LayerKey] = {},
    ) -> None: ...
    def add_layer(
        self,
        layer: typing.SupportsInt | typing.SupportsIndex,
        partition: PartitionId | int = ...,
        name: str = "",
    ) -> LayerView: ...
    @typing.overload
    def add_node(
        self, layer: LayerKey, node_id: NodeSymbol | int, attrs: NodeAttributes
    ) -> bool: ...
    @typing.overload
    def add_node(
        self,
        layer: typing.SupportsInt | typing.SupportsIndex,
        node_id: NodeSymbol | int,
        attrs: NodeAttributes,
        partition: PartitionId | int = ...,
    ) -> bool: ...
    @typing.overload
    def add_node(
        self, layer: str, node_id: NodeSymbol | int, attrs: NodeAttributes
    ) -> bool: ...
    def clear(self, include_mesh: bool = True) -> None: ...
    def clone(self) -> SceneGraph: ...
    def create_subgraph(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> SceneGraph: ...
    def empty(self) -> bool: ...
    def empty_like(self) -> SceneGraph: ...
    def find_edge(
        self, arg0: NodeSymbol | int, arg1: NodeSymbol | int
    ) -> SceneGraphEdge | None: ...
    def find_node(self, arg0: NodeSymbol | int) -> SceneGraphNode | None: ...
    def get_edge(
        self, arg0: NodeSymbol | int, arg1: NodeSymbol | int
    ) -> SceneGraphEdge: ...
    @typing.overload
    def get_labelspace(
        self,
        layer: typing.SupportsInt | typing.SupportsIndex,
        partition: typing.SupportsInt | typing.SupportsIndex = ...,
    ) -> Labelspace: ...
    @typing.overload
    def get_labelspace(self, name: str, resolve_layer: bool = True) -> Labelspace: ...
    @typing.overload
    def get_layer(
        self,
        layer: typing.SupportsInt | typing.SupportsIndex,
        partition: PartitionId | int = ...,
    ) -> LayerView: ...
    @typing.overload
    def get_layer(self, layer: str) -> LayerView: ...
    def get_layer_key(self, name: str) -> LayerKey: ...
    def get_node(self, arg0: NodeSymbol | int) -> SceneGraphNode: ...
    def get_position(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    def has_edge(self, arg0: NodeSymbol | int, arg1: NodeSymbol | int) -> bool: ...
    @typing.overload
    def has_layer(
        self,
        layer: typing.SupportsInt | typing.SupportsIndex,
        partition: PartitionId | int = ...,
    ) -> bool: ...
    @typing.overload
    def has_layer(self, layer: str) -> bool: ...
    def has_mesh(self) -> bool: ...
    def has_node(self, arg0: NodeSymbol | int) -> bool: ...
    @typing.overload
    def insert_edge(
        self,
        source: NodeSymbol | int,
        target: NodeSymbol | int,
        enforce_single_parent: bool = False,
    ) -> bool: ...
    @typing.overload
    def insert_edge(
        self,
        source: NodeSymbol | int,
        target: NodeSymbol | int,
        info: EdgeAttributes,
        enforce_single_parent: bool = False,
    ) -> bool: ...
    def num_edges(self, include_partitions: bool = True) -> int: ...
    def num_layers(self) -> int: ...
    def num_nodes(self, include_partitions: bool = True) -> int: ...
    def remove_edge(self, arg0: NodeSymbol | int, arg1: NodeSymbol | int) -> bool: ...
    def remove_layer(
        self,
        layer: typing.SupportsInt | typing.SupportsIndex,
        partition: PartitionId | int = ...,
    ) -> None: ...
    def remove_node(self, arg0: NodeSymbol | int) -> bool: ...
    def reset(
        self,
        arg0: collections.abc.Sequence[LayerKey],
        arg1: collections.abc.Mapping[str, LayerKey],
    ) -> None: ...
    def save(
        self, filepath: os.PathLike | str | bytes, include_mesh: bool = True
    ) -> None: ...
    @typing.overload
    def set_labelspace(
        self,
        labelspace: Labelspace,
        layer: typing.SupportsInt | typing.SupportsIndex,
        partition: typing.SupportsInt | typing.SupportsIndex = ...,
    ) -> None: ...
    @typing.overload
    def set_labelspace(
        self, labelspace: Labelspace, name: str, resolve_layer: bool = True
    ) -> None: ...
    def to_binary(self, include_mesh: bool = False) -> bytes: ...
    def transform(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]
    ) -> None: ...
    def update_from(
        self,
        arg0: SceneGraph,
        arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex],
    ) -> None: ...
    def update_from_binary(self, contents: bytes) -> bool: ...
    @property
    def edges(self) -> collections.abc.Iterator[SceneGraphEdge]: ...
    @property
    def interlayer_edges(self) -> collections.abc.Iterator[SceneGraphEdge]: ...
    @property
    def layer_ids(self) -> list[int]: ...
    @property
    def layer_keys(self) -> list[LayerKey]: ...
    @property
    def layer_names(self) -> dict[str, LayerKey]: ...
    @property
    def layer_partitions(self) -> collections.abc.Iterator[LayerView]: ...
    @property
    def layers(self) -> collections.abc.Iterator[LayerView]: ...
    @property
    def metadata(self) -> spark_dsg.Metadata: ...
    @property
    def node_lookup(self) -> dict[int, LayerKey]: ...
    @property
    def nodes(self) -> collections.abc.Iterator[SceneGraphNode]: ...
    @property
    def unpartitioned_edges(self) -> collections.abc.Iterator[SceneGraphEdge]: ...
    @property
    def unpartitioned_nodes(self) -> collections.abc.Iterator[SceneGraphNode]: ...

class SceneGraphEdge:
    info: EdgeAttributes
    def __repr__(self) -> str: ...
    @property
    def source(self) -> int: ...
    @property
    def target(self) -> int: ...

class SceneGraphLayer:
    @staticmethod
    def from_binary(arg0: bytes) -> SceneGraphLayer: ...
    @staticmethod
    def to_torch(
        G: SceneGraphLayer | LayerView,
        node_converter: typing.Callable[
            [SceneGraph | SceneGraphLayer | LayerView, SceneGraphNode], numpy.ndarray
        ],
        edge_converter: typing.Callable[
            [SceneGraph | SceneGraphLayer | LayerView, SceneGraphEdge], numpy.ndarray
        ]
        | None = None,
        double_precision: bool = False,
    ):
        """

        Convert a scene graph layer to a homogeneous pytorch geometric data structure.

        Args:
            G: scene graph layer to convert
            node_converter: function to generate input node features
            edge_converter: optional function to generate input edge features
            double_precision: whether or not output data attributes have double precision.

        Raises:
            ValueError: If pytorch geometric can't be found for the conversion

        Returns:
            pytorch_geometric.Data: homogeneous pytorch_geometric graph representing the
                scene graph layer.
        """
    @typing.overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @typing.overload
    def __init__(self, arg0: str) -> None: ...
    def add_node(self, arg0: NodeSymbol | int, arg1: NodeAttributes) -> None: ...
    def connected_components(self) -> list[list[int]]: ...
    def find_edge(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.SupportsInt | typing.SupportsIndex,
    ) -> SceneGraphEdge | None: ...
    def find_node(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> SceneGraphNode | None: ...
    def get_edge(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.SupportsInt | typing.SupportsIndex,
    ) -> SceneGraphEdge: ...
    def get_node(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> SceneGraphNode: ...
    def get_position(
        self, arg0: NodeSymbol | int
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    def has_edge(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.SupportsInt | typing.SupportsIndex,
    ) -> bool: ...
    def has_node(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool: ...
    @typing.overload
    def insert_edge(self, arg0: NodeSymbol | int, arg1: NodeSymbol | int) -> bool: ...
    @typing.overload
    def insert_edge(
        self, arg0: NodeSymbol | int, arg1: NodeSymbol | int, arg2: EdgeAttributes
    ) -> bool: ...
    def num_edges(self) -> int: ...
    def num_nodes(self) -> int: ...
    def remove_edge(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.SupportsInt | typing.SupportsIndex,
    ) -> bool: ...
    def shortest_path(
        self, arg0: NodeSymbol | int, arg1: NodeSymbol | int
    ) -> list[int]: ...
    def to_binary(self) -> bytes: ...
    @property
    def edges(self) -> collections.abc.Iterator[SceneGraphEdge]: ...
    @property
    def id(self) -> LayerKey: ...
    @property
    def nodes(self) -> collections.abc.Iterator[SceneGraphNode]: ...

class SceneGraphNode:
    def __repr__(self) -> str: ...
    def children(self) -> set[int]: ...
    def connections(self) -> list[int]: ...
    def get_parent(self) -> int | None: ...
    def has_children(self) -> bool: ...
    def has_parent(self) -> bool: ...
    def has_siblings(self) -> bool: ...
    def parents(self) -> set[int]: ...
    def siblings(self) -> set[int]: ...
    @property
    def attributes(self) -> NodeAttributes: ...
    @attributes.setter
    def attributes(self, NodeAttributes): ...
    @property
    def id(self) -> NodeSymbol: ...
    @property
    def layer(self) -> LayerKey: ...

class SemanticNodeAttributes(NodeAttributes):
    NO_SEMANTIC_LABEL: typing.ClassVar[int] = 4294967295
    bounding_box: BoundingBox
    name: str
    def __init__(self) -> None: ...
    @property
    def color(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.uint8], "[3, 1]"]: ...
    @color.setter
    def color(
        self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8, "[3, 1]"]
    ) -> None: ...
    @property
    def label_weights(self) -> dict[int, float]: ...
    @label_weights.setter
    def label_weights(
        self,
        arg0: collections.abc.Mapping[
            typing.SupportsInt | typing.SupportsIndex,
            typing.SupportsFloat | typing.SupportsIndex,
        ],
    ) -> None: ...
    @property
    def semantic_feature(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]: ...
    @semantic_feature.setter
    def semantic_feature(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]
    ) -> None: ...
    @property
    def semantic_label(self) -> int: ...
    @semantic_label.setter
    def semantic_label(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...

class TravNodeAttributes(NodeAttributes):
    def __init__(self) -> None: ...
    @property
    def first_observed_ns(self) -> int: ...
    @first_observed_ns.setter
    def first_observed_ns(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def last_observed_ns(self) -> int: ...
    @last_observed_ns.setter
    def last_observed_ns(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def max_radius(self) -> float: ...
    @max_radius.setter
    def max_radius(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def min_radius(self) -> float: ...
    @min_radius.setter
    def min_radius(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def radii(self) -> list[float]: ...
    @radii.setter
    def radii(
        self,
        arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex],
    ) -> None: ...
    @property
    def states(self) -> list[TraversabilityState]: ...
    @states.setter
    def states(self, arg0: collections.abc.Sequence[TraversabilityState]) -> None: ...

class TraversabilityNodeAttributes(NodeAttributes):
    boundary: BoundaryInfo
    def __init__(self) -> None: ...
    @property
    def distance(self) -> float: ...
    @distance.setter
    def distance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def first_observed_ns(self) -> int: ...
    @first_observed_ns.setter
    def first_observed_ns(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def last_observed_ns(self) -> int: ...
    @last_observed_ns.setter
    def last_observed_ns(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...

class TraversabilityState:
    """
    Members:

      UNKNOWN

      TRAVERSABLE

      INTRAVERSABLE

      TRAVERSED
    """

    INTRAVERSABLE: typing.ClassVar[
        TraversabilityState
    ]  # value = <TraversabilityState.INTRAVERSABLE: 2>
    TRAVERSABLE: typing.ClassVar[
        TraversabilityState
    ]  # value = <TraversabilityState.TRAVERSABLE: 1>
    TRAVERSED: typing.ClassVar[
        TraversabilityState
    ]  # value = <TraversabilityState.TRAVERSED: 3>
    UNKNOWN: typing.ClassVar[
        TraversabilityState
    ]  # value = <TraversabilityState.UNKNOWN: 0>
    __members__: typing.ClassVar[
        dict[str, TraversabilityState]
    ]  # value = {'UNKNOWN': <TraversabilityState.UNKNOWN: 0>, 'TRAVERSABLE': <TraversabilityState.TRAVERSABLE: 1>, 'INTRAVERSABLE': <TraversabilityState.INTRAVERSABLE: 2>, 'TRAVERSED': <TraversabilityState.TRAVERSED: 3>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(
        self, state: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class _Metadata:
    def __init__(self) -> None: ...
    def _add(self, arg0: str) -> None: ...
    def _get(self) -> str: ...
    def _set(self, arg0: str) -> None: ...

def colorbrewer_color(arg0: typing.SupportsInt | typing.SupportsIndex) -> Color: ...
def compute_ancestor_bounding_box(
    G: SceneGraph,
    node_id: typing.SupportsInt | typing.SupportsIndex,
    depth: typing.SupportsInt | typing.SupportsIndex = 1,
    bbox_type: BoundingBoxType = ...,
) -> BoundingBox: ...
def distinct_150_color(arg0: typing.SupportsInt | typing.SupportsIndex) -> Color: ...
def enable_short_serialization_message(enable: bool = True) -> None: ...
def get_2d_convex_hull(
    arg0: collections.abc.Sequence[
        typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]
    ],
) -> list[int]: ...
def get_min_2d_box(
    points: collections.abc.Sequence[
        typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]
    ],
    hull: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = [],
) -> BoxResult2D | None: ...
def rainbow_color(
    id: typing.SupportsInt | typing.SupportsIndex,
    ids_per_revolution: typing.SupportsInt | typing.SupportsIndex = 16,
) -> Color: ...
def version() -> str: ...
